# Primera etapa: Build de la aplicación
FROM node:18-alpine AS build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build && ls -la /app/dist

FROM nginx:stable-alpine AS production-stage

COPY ./docker/nginx.conf /etc/nginx/nginx.conf

#COPY --from=build-stage /app /app

COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]